Fjm create post
fmings/rare-client-nextjs pull request #27
Opened 2024-08-11 22:40 UTC by fmings

files and functions to create post
currently publicationDate and userId are set to static values and need to be updated to host actual date/time
**Not sure userId can be set to dynamic value since there is no login

2024-08-11 23:07 UTC, FletcherJMoore approved these changes
<img src="https://media2.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif"/>

2024-08-11 23:38 UTC, britnay268 commented on components/forms/PostForm.js
> +    const payload = { ...formInput, userId: 1, publicationDate: Date.now };
Instead of Date.now - use new Date() and remove the userId

2024-08-11 23:39 UTC, britnay268 commented on components/forms/PostForm.js
> +
We can insert a user dropdown to assign the right userId/user to the post.      
<FloatingLabel controlId="floatingSelect" label="User">
        <Form.Select
          aria-label="User"
          name="userId"
          onChange={handleChange}
          className="mb-3"
          // CHANGED KEY TO FORMINPUT VERSUS OBJ
          value={formInput.userId}
          required
        >
          <option value="">Select the user creating the Post</option>
          {
          users.map((u) => (
            <option
              key={u.id}
              value={u.id}
            >
              {u.firstName} {u.lastName}
            </option>
          ))
        }
        </Form.Select>
      </FloatingLabel>

2024-08-11 23:41 UTC, britnay268 requested changes

2024-08-11 23:41 UTC, britnay268 commented on components/forms/PostForm.js
> +
Probably create a state for users to store all users like what was done for categories.

2024-08-12 01:37 UTC, Zpcolburn approved these changes
Works just as it needs to.

2024-08-12 01:51 UTC, britnay268 approved these changes

2024-08-12 21:05 UTC, merged